stages:
  create_partitions:
    cmd: python prepare_data.py
    deps:
      - data
      - prepare_data.py
    outs:
      - partitions/train.csv
      - partitions/validation.csv
  build:
    cmd: python train.py -e 200 -lr 0.3
    deps:
      - data
      - train.py
      - partitions/train.csv
    outs:
      - models/linear_regression_200_0.3.pt
      - metrics/train_loss_200_0.3.png
    metrics:
      - metrics/train_loss_200_0.3.txt:
            cache: false
  single_eval:
    cmd: python eval.py -e 200 -lr 0.3
    deps:
      - data
      - eval.py
      - partitions/validation.csv
    outs:
    -  evaluations/chart_200_0.3.png
  train:
    foreach:
      - epochs: 500
        lr: 0.003
      - epochs: 1000
        lr: 0.001
      - epochs: 1500
        lr: 0.0001
      - epochs: 2000
        lr: 0.03
    do:
      cmd: python train.py -e ${item.epochs} -lr ${item.lr}  
      deps:
        - data
        - train.py
        - partitions/train.csv
      outs:
        - models/linear_regression_${item.epochs}_${item.lr}.pt
        - metrics/train_loss_${item.epochs}_${item.lr}.png
      metrics:
        - metrics/train_loss_${item.epochs}_${item.lr}.txt:
            cache: false
  eval:
    foreach:
      - epochs: 500
        lr: 0.003
      - epochs: 1000
        lr: 0.001
      - epochs: 1500
        lr: 0.0001
      - epochs: 2000
        lr: 0.03
    do:
      cmd: python eval.py -e ${item.epochs} -lr ${item.lr}
      deps:
        - data
        - eval.py
        - partitions/validation.csv
      outs:
      -  evaluations/chart_${item.epochs}_${item.lr}.png